import com.google.gson.Gson;
import org.junit.Test;
import static org.junit.Assert.assertEquals;

public class BlackMirrorTest {

    @Test
    public void simpleEpisode() throws Exception {
        Gson gson = new Gson();
        assertEquals("{\"id\":1281043,\"url\":\"http://www.tvmaze.com/episodes/1281043/black-mirror-4x05-metalhead\",\"name\":\"Metalhead\",\"season\":4,\"number\":5,\"airdate\":\"2017-12-29\",\"airtime\":\"\",\"airstamp\":\"2017-12-29T12:00:00+00:00\",\"runtime\":41,\"image\":{\"medium\":\"http://static.tvmaze.com/uploads/images/medium_landscape/140/350996.jpg\",\"original\":\"http://static.tvmaze.com/uploads/images/original_untouched/140/350996.jpg\"},\"summary\":\"<p>In a post-apocalyptic England, three scavengers break into a warehouse. Two of them are killed by a robot \\\"dog\\\" drone, which relentlessly hunts the survivor.</p>\",\"_links\":{\"self\":{\"href\":\"http://api.tvmaze.com/episodes/1281043\"}}}",
                TvTime.parseEpisode("{\"id\":1281043,\"url\":\"http://www.tvmaze.com/episodes/1281043/black-mirror-4x05-metalhead\",\"name\":\"Metalhead\",\"season\":4,\"number\":5,\"airdate\":\"2017-12-29\",\"airtime\":\"\",\"airstamp\":\"2017-12-29T12:00:00+00:00\",\"runtime\":41,\"image\":{\"medium\":\"http://static.tvmaze.com/uploads/images/medium_landscape/140/350996.jpg\",\"original\":\"http://static.tvmaze.com/uploads/images/original_untouched/140/350996.jpg\"},\"summary\":\"<p>In a post-apocalyptic England, three scavengers break into a warehouse. Two of them are killed by a robot \\\"dog\\\" drone, which relentlessly hunts the survivor.</p>\",\"_links\":{\"self\":{\"href\":\"http://api.tvmaze.com/episodes/1281043\"}}}"));
    }

    @Test
    public void multipleEpisodes() throws Exception {
        assertEquals("[{\"id\":30902,\"url\":\"http://www.tvmaze.com/episodes/30902/black-mirror-1x01-the-national-anthem\",\"name\":\"The National Anthem\",\"season\":1,\"number\":1,\"airdate\":\"2011-12-04\",\"airtime\":\"\",\"airstamp\":\"2011-12-04T12:00:00+00:00\",\"runtime\":44,\"image\":{\"medium\":\"http://static.tvmaze.com/uploads/images/medium_landscape/13/33511.jpg\",\"original\":\"http://static.tvmaze.com/uploads/images/original_untouched/13/33511.jpg\"},\"summary\":\"<p>Prime Minister Michael Callow faces a huge and shocking dilemma when Princess Susannah, a much-loved member of the Royal Family, is kidnapped.</p>\",\"_links\":{\"self\":{\"href\":\"http://api.tvmaze.com/episodes/30902\"}}},{\"id\":30903,\"url\":\"http://www.tvmaze.com/episodes/30903/black-mirror-1x02-fifteen-million-merits\",\"name\":\"Fifteen Million Merits\",\"season\":1,\"number\":2,\"airdate\":\"2011-12-11\",\"airtime\":\"\",\"airstamp\":\"2011-12-11T12:00:00+00:00\",\"runtime\":61,\"image\":{\"medium\":\"http://static.tvmaze.com/uploads/images/medium_landscape/13/33512.jpg\",\"original\":\"http://static.tvmaze.com/uploads/images/original_untouched/13/33512.jpg\"},\"summary\":\"<p>In the near future, everyone is confined to a life of strange physical drudgery. The only way to escape is to enter the 'Hot Shot' talent show and pray you can impress the judges.</p>\",\"_links\":{\"self\":{\"href\":\"http://api.tvmaze.com/episodes/30903\"}}}]",
                TvTime.parseEpisodes("[{\"id\":30902,\"url\":\"http://www.tvmaze.com/episodes/30902/black-mirror-1x01-the-national-anthem\",\"name\":\"The National Anthem\",\"season\":1,\"number\":1,\"airdate\":\"2011-12-04\",\"airtime\":\"\",\"airstamp\":\"2011-12-04T12:00:00+00:00\",\"runtime\":44,\"image\":{\"medium\":\"http://static.tvmaze.com/uploads/images/medium_landscape/13/33511.jpg\",\"original\":\"http://static.tvmaze.com/uploads/images/original_untouched/13/33511.jpg\"},\"summary\":\"<p>Prime Minister Michael Callow faces a huge and shocking dilemma when Princess Susannah, a much-loved member of the Royal Family, is kidnapped.</p>\",\"_links\":{\"self\":{\"href\":\"http://api.tvmaze.com/episodes/30902\"}}},{\"id\":30903,\"url\":\"http://www.tvmaze.com/episodes/30903/black-mirror-1x02-fifteen-million-merits\",\"name\":\"Fifteen Million Merits\",\"season\":1,\"number\":2,\"airdate\":\"2011-12-11\",\"airtime\":\"\",\"airstamp\":\"2011-12-11T12:00:00+00:00\",\"runtime\":61,\"image\":{\"medium\":\"http://static.tvmaze.com/uploads/images/medium_landscape/13/33512.jpg\",\"original\":\"http://static.tvmaze.com/uploads/images/original_untouched/13/33512.jpg\"},\"summary\":\"<p>In the near future, everyone is confined to a life of strange physical drudgery. The only way to escape is to enter the 'Hot Shot' talent show and pray you can impress the judges.</p>\",\"_links\":{\"self\":{\"href\":\"http://api.tvmaze.com/episodes/30903\"}}}]"));
    }

}
